steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/web', '.' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/web' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'pull', 'mongo:latest' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'pull', 'redis:latest' ]

  - name: 'gcr.io/cloud-builders/kubectl'
    args: [ 'apply', '-f', 'k8s-deployment.yaml' ]
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=ai-cluster'

images:
  - 'gcr.io/$PROJECT_ID/web'