version: "3.8"
services:
  web:
    env_file:
      - .env.docker
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=mongodb://db:27017
      - REDIS_URL=redis://redis:6379

  db:
    image: mongo:latest
    container_name: mongodb_${ENV:-dev}
    ports:
      - '${MONGO_PORT:-27017}:27017'

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf