apiVersion: apps/v1
kind: Deployment
metadata:
  name: DeployGKE
spec:
  template:
    spec:
      containers:
        - name: web
          image: gcr.io/$PROJECT_ID/web
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-api-key
                  key: OPENAI_API_KEY